[package]
name = "rusted-ruins-map-generator"
version = "0.1.0"
authors = ["T. Okubo <t.okubo.rx78+devel@gmail.com>"]

[lib]
name = "rusted_ruins_map_generator"
crate-type = ["rlib"]

[dependencies.rusted-ruins-array2d]
path = "../array2d"

[dependencies]
rand = "0.3"
