[package]
name = "rusted-ruins"
version = "0.0.1"
authors = ["T. Okubo <t.okubo.rx78+devel@gmail.com>"]

[dependencies]
lazy_static = "1"
failure = "0.1.1"
tar = "0.4"
serde = "1"
serde_derive = "1"
toml = "0.4"
log = "0.4"
env_logger = "0.5"
walkdir = "2"

[dependencies.rusted-ruins-array2d]
path = "../array2d"

[dependencies.rusted-ruins-common]
path = "../common"
features = ["global_state_obj"]

[dependencies.rusted-ruins-audio]
path = "../audio"

[dependencies.rusted-ruins-rng]
path = "../rng"

[dependencies.rusted-ruins-rules]
path = "../rules"

[dependencies.rusted-ruins-map-generator]
path = "../map-generator"

[dependencies.sdl2]
version = "0.31"
default-features = false
features = ["ttf", "image"]
