[package]
name = "rusted-ruins-map-editor"
version = "0.3.0"
edition = "2018"
authors = ["T. Okubo <t.okubo.rx78+devel@gmail.com>"]

[dependencies]
rusted-ruins-array2d = { path = "../array2d" }
rusted-ruins-common = { path = "../common", features = ["global_state_obj"] }

gtk = { version = "0.5", features = ["v3_10"] }
gdk = "0.9"
gio = "0.5"
gdk-pixbuf = "0.5"
cairo-rs = "0.5"
tar = "0.4"

