
[normal]
return = "Enter"
d = "DrinkItem"
e = "EatItem"
i = "Openitemmenu"
p = "PickUpItem"
s = "OpenStatusWin"
w = "OpenEquipWin"
escape = "OpenExitWin"

[dialog]
return = "Enter"
escape = "Cancel"
tab = "RotateWindowRight"
