[package]
name = "rusted-ruins-makepak"
version = "0.1.0"
authors = ["T. Okubo <t.okubo.rx78+devel@gmail.com>"]

[dependencies]
serde = "1"
serde_derive = "1"
error-chain = "0.11"
toml = "0.4"
tar = "0.4"
getopts = "0.2"
image = "0.18"

[dependencies.rusted-ruins-array2d]
path = "../array2d"

[dependencies.rusted-ruins-common]
path = "../common"


