[package]
name = "rusted-ruins-makepak"
version = "0.1.0"
authors = ["T. Okubo <t.okubo.rx78+devel@gmail.com>"]

[dependencies]
serde = "1"
serde_derive = "1"
failure = "0.1.1"
toml = "0.4"
tar = "0.4"
clap = "2"
image = "0.20"

[dependencies.rusted-ruins-array2d]
path = "../array2d"

[dependencies.rusted-ruins-common]
path = "../common"


