[package]
name = "rusted-ruins-rules"
version = "0.1.0"
authors = ["T. Okubo <t.okubo.rx78+github@gmail.com>"]

[lib]
name = "rusted_ruins_rules"
crate-type = ["rlib"]

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"
log = "0.3"
lazy_static = "0.2"

[dependencies.rusted-ruins-common]
path = "../common"
